return {
  "zbirenbaum/copilot.lua",
  cmd = "Copilot",
  build = ":Copilot auth",
  opts = {
    panel = { enabled = false },
    suggestion = {
      enabled = false,
      auto_trigger = true,
      debounce = 75,
      keymap = {
        accept = "<M-p>",
        accept_word = "<M-w>",
        accept_line = "<M-l>",
        next = "<M-]>",
        prev = "<M-[>",
        dismiss = "<C-]>",
      },
    },
    filetypes = {
      ["*"] = false,
      python = true,
      lua = true,
      go = true,
      rust = true,
      html = true,
      -- c = true,
      -- cpp = true,
      java = true,
      javascript = true,
      typescript = true,
      javascriptreact = true,
      typescriptreact = true,
      svelte = true,
      cs = true,
      terraform = true,
      dockerfile = true,
      markdown = true,
      sql = true,
      sh = true,
      perl = true,
    },
  },
}
